spring:
  application:
    name: ElectronicWallet
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/electronicwallet
    username: root
    password: 1234

#mybatis配置
mybatis:
  configuration:
    #日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名自动映射开关
    map-underscore-to-camel-case: true

    #123456

    #1
    #32
    #224